#!/bin/bash

set -eu

# set_chocpkg_root sets the CHOCPKG_ROOT environment variable based on the
# path where the script is located.
chocpkg::set_root() {
    # Assume that the package root is one directory up from the script.
    if [[ "$0" = /* ]]; then
        local script_path="$0"
    else
        local script_path="$PWD/${0#./}"
    fi
    local script_dir=$(dirname "$script_path")
    CHOCPKG_ROOT=$(dirname "$script_dir")

    # Build directory must not contain a space, or bad things happen:
    if [[ "$CHOCPKG_ROOT" = *\ * ]]; then
        cat <<END
        The build scripts are in a path containing a space:

            $CHOCPKG_ROOT

        Builds will probably fail - try moving the build scripts to a
        different directory not containing a space.
END
        exit 1
    fi
}

if [ -z "${CHOCPKG_ROOT:-}" ]; then
    chocpkg::set_root
fi

# Ordering here matters, since we rely on basic setup of standard variables
# in commands.sh for some of the evaluation in buildenv.sh:
. "$CHOCPKG_ROOT/chocpkg/commands.sh"
. "$CHOCPKG_ROOT/buildenv.sh"

chocpkg::commands::command "$@"

